local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("reset", {
    t("* {"),
    t({ "", "    margin: 0;" }),
    t({ "", "    padding: 0;" }),
    t({ "", "    box-sizing: border-box;" }),
    t({ "", "    -webkit-appearance: none;" }),
    t({ "", "    -moz-appearance: none;" }),
    t({ "", "    appearance: none;" }),
    t({ "", "}" }),
    t({ "", "*:focus {" }),
    t({ "", "    outline: none;" }),
    t({ "", "}" }),
    t({ "", "input::-webkit-outer-spin-button," }),
    t({ "", "input::-webkit-inner-spin-button {" }),
    t({ "", "    -webkit-appearance: none;" }),
    t({ "", "}" }),
    t({ "", "input[type='number'] {" }),
    t({ "", "    appearance: none;" }),
    t({ "", "    -moz-appearance: textfield;" }),
    t({ "", "}" }),
    i(0),
  }),

  s("twreset", {
    t("@import 'tailwindcss';"),
    t({ "", "" }),
    t("@layer base {"),
    t({ "", "  :root {" }),
    t({ "", "    @apply h-full;" }),
    t({ "", "    touch-action: pan-x pan-y;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  @media (prefers-color-scheme: dark), (prefers-color-scheme: light) {"),
    t({ "", "    :root {" }),
    t({ "", "      color-scheme: light;" }),
    t({ "", "    }" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  * {"),
    t({ "", "    @apply m-0 box-border appearance-none p-0 focus:outline-none;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  html {"),
    t({ "", "    @apply touch-pan-y;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  input::-webkit-outer-spin-button,"),
    t({ "", "  input::-webkit-inner-spin-button {" }),
    t({ "", "    @apply appearance-none;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  input[type='number'] {"),
    t({ "", "    @apply appearance-none;" }),
    t({ "", "    appearance: textfield;" }),
    t({ "", "    -moz-appearance: textfield;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  img {"),
    t({ "", "    @apply pointer-events-none select-none;" }),
    t({ "", "  }" }),
    t({ "", "}" }),
    i(0),
  }),
}
