local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("reset", {
    t("* {"),
    t({ "", "    margin: 0;" }),
    t({ "", "    padding: 0;" }),
    t({ "", "    box-sizing: border-box;" }),
    t({ "", "    -webkit-appearance: none;" }),
    t({ "", "    -moz-appearance: none;" }),
    t({ "", "    appearance: none;" }),
    t({ "", "}" }),
    t({ "", "*:focus {" }),
    t({ "", "    outline: none;" }),
    t({ "", "}" }),
    t({ "", "input::-webkit-outer-spin-button," }),
    t({ "", "input::-webkit-inner-spin-button {" }),
    t({ "", "    -webkit-appearance: none;" }),
    t({ "", "}" }),
    t({ "", "input[type='number'] {" }),
    t({ "", "    appearance: none;" }),
    t({ "", "    -moz-appearance: textfield;" }),
    t({ "", "}" }),
    i(0),
  }),

  s("twreset", {
    t("@import 'tailwindcss';"),
    t({ "", "" }),
    t("@layer base {"),
    t({ "", "  :root {" }),
    t({ "", "    @apply h-full;" }),
    t({ "", "    touch-action: none;" }),
    t({ "", "    -webkit-tap-highlight-color: transparent;" }),
    t({ "", "    text-rendering: optimizeLegibility;" }),
    t({ "", "    -webkit-font-smoothing: antialiased;" }),
    t({ "", "    -moz-osx-font-smoothing: grayscale;" }),
    t({ "", "    scroll-behavior: smooth;" }),
    t({ "", "    -ms-touch-action: none;" }),
    t({ "", "    -webkit-touch-callout: none;" }),
    t({ "", "    zoom: 1;" }),
    t({ "", "    -moz-transform: scale(1);" }),
    t({ "", "    -webkit-transform: scale(1);" }),
    t({ "", "    transform: scale(1);" }),
    t({ "", "    -ms-zoom: 1;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  @media (prefers-color-scheme: dark) {"),
    t({ "", "    :root {" }),
    t({ "", "      color-scheme: light;" }),
    t({ "", "    }" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  @media (prefers-color-scheme: light) {"),
    t({ "", "    :root {" }),
    t({ "", "      color-scheme: light;" }),
    t({ "", "    }" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  * {"),
    t({ "", "    @apply m-0 box-border appearance-none p-0 focus:outline-none will-change-auto;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  body {"),
    t({ "", "    @apply min-h-full;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  button, label, summary, [role='button'] {"),
    t({ "", "    @apply cursor-pointer select-none touch-none;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  input[type='checkbox'],"),
    t({ "", "  input[type='radio'] {" }),
    t({ "", "    @apply appearance-auto;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  html {"),
    t({ "", "    @apply touch-none;" }),
    t({ "", "    -webkit-text-size-adjust: 100%;" }),
    t({ "", "    -ms-text-size-adjust: 100%;" }),
    t({ "", "    -moz-text-size-adjust: 100%;" }),
    t({ "", "    text-size-adjust: 100%;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  input::-webkit-outer-spin-button,"),
    t({ "", "  input::-webkit-inner-spin-button {" }),
    t({ "", "    @apply appearance-none;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  input[type='number'] {"),
    t({ "", "    @apply appearance-none;" }),
    t({ "", "    appearance: textfield;" }),
    t({ "", "    -moz-appearance: textfield;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  img, video, canvas, svg {"),
    t({ "", "    @apply block max-w-full h-auto;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  img {"),
    t({ "", "    @apply pointer-events-none select-none will-change-auto;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  [data-loading] {"),
    t({ "", "    @apply will-change-transform;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  a {"),
    t({ "", "    @apply text-inherit no-underline;" }),
    t({ "", "  }" }),
    t({ "", "" }),
    t("  textarea {"),
    t({ "", "    @apply resize-none;" }),
    t({ "", "  }" }),
    t({ "", "}" }),
    i(0),
  }),
}
